### ISSUE TITLE
Peer-to-Peer Code Review

### ISSUE THREAD

**Issue by Anjacodes** [fabianofrank/todolist#3]
Good job on making a very neat copy of the to-do list! 

Here are some ideas on what could be improved: 

* Export your function from the status file in order to be able to use it in index.js
* I think you might need to use a loop for the checkboxes since there will be several checkboxes and you will need to give items.completed some kind of index to differentiate which item you would like to mark as completed.
* Identify the part of the code that is getting the info from HTML which is causing output error when trying to dynamically create new tasks.

**Comment by fabianofrank** [comment]
Thanks for the feedback, it was really helpful!
